= References
:hardbreaks:

References are somewhat different in Conical compared to other languages. In that when you take a reference of a variable, you actually are taking a reference to the data that the variable contains.
[source, conical]
----
struct Foo {
    a: i32;
    b: i32;
}
----

[source, conical]
----
mut data: &Foo = new Foo{1,2};
let ref1: &Foo = &data;
let ref2: &Foo = &ref1;
----

lets go through this line-by-line
[source, conical]
mut data: &Foo = new Foo{1,2};

This line declares a mutable variable `data` and assigns it to a newly allocated Foo struct. It also includes an optional initializer. If left off everything is initialized to default values.
[NOTE]
the `new` syntax is likely to change

[source, conical]
let ref1: &Foo = &data;

Then we declare another variable `ref1` (constant this time) and assign a reference to data to it. Notice that the type is still `&Foo` instead of `&&Foo`, this is because the reference operator `&` takes the reference of the memory that the variable _points_ to instead of the variable itself (you can use the referent operator `^` to do this).

[source, conical]
let ref2: &Foo = &ref1;

This is just another example of taking a reference, note that the actual value of the reference is still the *same*. The reference operator is required whenever you want to create a binding with a reference as its value.

At the end of this scope if none of the references are returned (and/or if none of them were passed in as parameters) then the memory that was originally created is freed.

[NOTE]
Conical uses Static Reference Counting to automatically manage memory, you can find more information (here)[]
