= Static Reference Counting
:hardbreaks:

In Conical when you take a reference to data created with `new` an internal reference counter is incremented within the compiler. Then whenever a reference to some data goes out of scope that counter is decremented. When the counter hits zero the compiler inserts the necessary code to free that data. 

[NOTE]
The normal abbreviation of Static Reference Counting is SRC, however to distinguish it from the abbreviation for source, the documentation will use the abbreviation SRFC.

The biggest criticism of SRFC is that it cannot handle cyclical references, or references that refer to each other thereby making it impossible for the counter to hit zero.
Conical solves this by keeping an internal graph of the dependencies types have on each other. It then checks the graph for cycles, and if it finds one it will generate an error.
Note that all of this happens *at compile time* thus making it a "zero-cost abstraction" (though it does unfortunately increase build times)

For example, we will start by defining a struct that could contain a possible cycle.
[source, conical]
----
struct Cycle {
    next: &Cycle;
}
----
As it stands this will fail to compile since it could be used to make a cyclical dependency that would cause the memory to never be freed. 
To fix this we can add a lifetime annotation.

[source, conical]
----
struct Cycle<'a> {
    next: &<'a> Cycle;
}
----

This requires every allocation of this struct to have an explicit lifetime.

[source, conical]
----
fn example() {
    mut cycle = new Cycle<'this>;
    let cycle2 = new Cycle<'cycle>{&cycle};
    cycle.next = &cycle;
}
----
This now removes the role of the reference counter, since the lifetime of the data is now explicitly defined.
The <'this> lifetime is a builtin lifetime that refers to the current scope. So in the example the two Cycle structs will be freed at the end of the function.

What separates conical's lifetime annotations from rust's is that instead of having to annotate each function, you can just use the identifier of the function (or any other variable) to set it to that lifetime.
In the example above cycle2's lifetime is 'cycle which means it takes its lifetime from cycle (which is 'this). The generic-like lifetime annotations are also supported if a function needs explicit lifetimes to be passed in.
You can also annotate blocks with labels and use those as lifetimes, which is useful for deeply nested data.
[source, conical]
----
fn example() {
    foo: {
        bar: {
            mut data = new Cycle<'foo>;
        }
    }
}
----

There is also <'parent> and <'static> lifetimes, where 'parent refers to the scope above the current one and is automatically assigned to references that are passed as parameters and returned from functions, and 'static refers to the runtime of the entire program but cannot be used manually (global variables and constants use this automatically). 


