= Structs
:hardbreaks:

Structs in Conical are defined using the `struct` keyword followed by a name and a body.

[source, conical]
----
struct Foo {
    a: i32;
    b: i32;
}
----

structs can *only* contain data. To associate a particular function with a struct an `impl` block can be used. 
[source, conical]
----
struct Foo {
    a: i32;
    b: i32;
}

impl Foo {
    fn create(a: i32, b: i32) -> Self {
        Foo {a, b}
    }
}

fn main() {
    let foo: Foo = Foo::create(3, 4);
    dbg!(foo);
}
----

let walk through this:

firstly we have our struct definition as before:
[source, conical]
struct Foo {...}

then we have our implementation block (or impl block) that defines a function `create` that takes in two integers `a` and `b` and returns a new instance of Foo. 
In impl blocks `Self` and `self` are defined as the type being implemented and a reference to that type.

finally we have our `main` function that acts as the entrypoint into our program.
first we create a new Foo structure using the previous function `create`. Notice that it uses `Foo::create` instead of `Foo.create`. This is because the dot operator (when calling a function) passes the left side as a value to the function on the right. To show this lets create a new function for Foo called `greater_then`

[source, conical]
----
impl Foo {
    //... our previous function
    
    fn greater_then(&self) -> bool {
        self.a > self.b
    }
}
----

The `greater_then` function takes in a reference to `self`, notice that you do not have to define the type after self, this is because it is implied. it is functionally equivalent to `self: &Foo`. Also notice that there is no `return` keyword being used, this is because in conical everything is an ()[expression]

You can also use an `impl` block to implement a specefic trait for a type. For example the `Show` trait (owing its origins to haskell) allows a struct to be printed using any of the printx! macros. It defines one method `to_string`, that takes in a reference to self and an ()[allocator] and returns a ()[string] reference.
[source, conical]
----
impl Show for Foo {
    fn to_string(&self, allocator: Allocator) -> &str {
        format!("{{ a: {self.a}, b: {self.b} }}", allocator: allocator)
    }
}
----

All trait functions must be implemented to compile.

